### ISSUE TITLE
I have created the env but?

### ISSUE THREAD

**Issue by vpsbykaif** [Akash98Sky/gemi-bot#10]
I have created the env in the front of the project but it still have this issue:

![Screenshot_20240304_232648_Termius](https://github.com/Akash98Sky/gemi-bot/assets/149788775/c793454e-4cc7-4748-9cf1-b445b055b138)

**Comment by Akash98Sky** [comment]
- What command are you executing to run the application?
- In which directory are you running the command?

**Comment by vpsbykaif** [comment]
- I an executing 'gunicorn main:web_app --bind 0.0.0.0:8080 -k aiohttp.GunicornWebWorker' .

- The directory which I execute the code is 'root/gemi-bot' the env file is in the 'gemi-bot folder'.


![Screenshot_20240305_070810_Termius](https://github.com/Akash98Sky/gemi-bot/assets/149788775/3ecfd7a9-d056-42b7-a439-ed86a9e3fcdf)

**Comment by Akash98Sky** [comment]
Ok, try running the app in a venv.

Run these command in the application root folder (/root/gemi-bot)
1. `python -m venv venv`
2. `source venv/bin/activate`
3. `gunicorn main:web_app --bind 0.0.0.0:8080 -k aiohttp.GunicornWebWorker`

**Comment by Akash98Sky** [comment]
This should be fixed now.
